default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: protospace_41260_development

test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: protospace_41260_test

production:
  <<: *default
  adapter: postgresql
  url: postgresql://protospace_41261_user:xxqJIvAZFZRVTXhBxYSKNH3LxpV3JWkD@dpg-cq88ecaj1k6c73cg6ahg-a.oregon-postgres.render.com/protospace_41261